### ISSUE TITLE
Выдает ошибку

### ISSUE THREAD

**Issue by rsvega** [TheMaxMur/vk-bot-for-homework#1]
``` ошибка ```
не работает
![image](https://user-images.githubusercontent.com/73408553/97095250-ca82a680-1665-11eb-81ed-15db757374a0.png)

**Comment by TheMaxMur** [comment]
Исправил, ошибка была в том, что файл homework.txt был наполнен информацией, и из-за того, что в linux и windows различаются кодировки текста, он не понимал, что там написано. Очистил файл с домашкой, теперь данная проблема не должна больше возникать.
